development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: denvyyard_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: denvyyard_production
  pool: 5
  timeout: 5000
